### ISSUE TITLE
Update not working for dependecy installed from GIT hidden ref if ref comes from a fork

### ISSUE THREAD

**Issue by lmignon** [sbidoul/pip-deepfreeze#48] opened 2020-08-24 13:36 UTC
Github allows you to reference a pull request as a hidden ref you can fetch. This feature is useful to keep a log of you open PR required by your project.

In order to declare a dependency to a new patched version of one of my project's dependencies, I've added into my requirements.txt.in the following line:
```
odoo10-addon-account-banking-mandate @ git+https://github.com/oca/bank-payment.git@refs/pull/727/head#subdirectory=setup/account_banking_mandate
```

and used the update command to install and freeze this new version of my dependency
` pip-df sync --update odoo10-addon-account-banking-mandate `

(PR from acsone/bank-payment  to oca/bank-payment)

At the end of the process, the dependency is correctly installed however the updated entry into my  `requirements.txt` file is not right. Indeed, even if the sha is the right one, the ORG into the github url is the one on which the pr has been made not the one from which the changes are submitted.... 
```
odoo10-addon-account-banking-mandate @ git+https://github.com/oca/bank-payment.git@84d5fd2cc8c9bbca6b036ad5f8d87776d1b3fdad#subdirectory=setup/account_banking_mandate
```

Is-it a know limitation or a bug?

**Comment by sbidoul** [comment] 2020-08-27 15:55
Indeed

```console
$ pip install "odoo10-addon-account-banking-mandate @ git+https://github.com/oca/bank-payment.git@84d5fd2cc8c9bbca6b036ad5f8d87776d1b3fdad#subdirectory=setup/account_banking_mandate"
Collecting odoo10-addon-account-banking-mandate@ git+https://github.com/oca/bank-payment.git@84d5fd2cc8c9bbca6b036ad5f8d87776d1b3fdad#subdirectory=setup/account_banking_mandate
  Cloning https://github.com/oca/bank-payment.git (to revision 84d5fd2cc8c9bbca6b036ad5f8d87776d1b3fdad) to /tmp/pip-install-vN6Ygs/odoo10-addon-account-banking-mandate
  Running command git clone -q https://github.com/oca/bank-payment.git /tmp/pip-install-vN6Ygs/odoo10-addon-account-banking-mandate
  Running command git checkout -q 84d5fd2cc8c9bbca6b036ad5f8d87776d1b3fdad
  fatal: reference is not a tree: 84d5fd2cc8c9bbca6b036ad5f8d87776d1b3fdad
ERROR: Command errored out with exit status 128: git checkout -q 84d5fd2cc8c9bbca6b036ad5f8d87776d1b3fdad Check the logs for full command output.
```

This issue can probably be addressed in pip.

The issue is that the commit is not directly reachable after a git clone.

One possibility could be to do something around [here](https://github.com/pypa/pip/blob/0b18e21cbe64b1bd089e280fd8ba592cdbfcac61/src/pip/_internal/vcs/git.py#L240-L243), such as a `git ls-remote` to see if the commit exists when the first checkout attempt has failed.

**Comment by sbidoul** [comment] 2020-08-28 07:21
The bottom of the issue is that most git servers (and GitHub in particular) do not allow fetching arbitrary commits. Even if pip would try to be smart to find the commit with git ls-remote, it would lose access to it as soon as someone would add a commit to the original pull request. So that is probably not a very useful change to do in pip.

At the end of the day, one must make sure that all commits referenced in `requirements.txt` are and remain reachable via a branch or a tag.

**Comment by lmignon** [comment] 2020-08-28 08:08
I share this thought. The correct use is therefore to avoid using hidden ref. We must always use a reference that remain reachable..

**Comment by sbidoul** [comment] 2020-08-28 08:26
@lmignon it is true that one must make sure that the commits referenced in `requirements.txt` remain reachable.

However in the case you mention, the commit *is* reachable via a git fetch.

So I think this is worth fixing in pip. I created an issue (https://github.com/pypa/pip/issues/8815) and I'll come up with a PR.

**Comment by sbidoul** [comment] 2020-08-31 07:52
@lmignon This should work fine with https://github.com/pypa/pip/pull/8817.

Now the last missing piece of the puzzle is the tool that places tags on all commits referenced in requirements.txt, and to do that automatically pushes them to an org where the user has right to create tags. I'm not sure this should be part of pip-deepfreeze. It would probably be best as a standalone tool.

**Comment by lmignon** [comment] 2020-08-31 08:24
> @lmignon This should work fine with [pypa/pip#8817](https://github.com/pypa/pip/pull/8817).
> 

great! :champagne: 

> Now the last missing piece of the puzzle is the tool that places tags on all commits referenced in requirements.txt, and to do that automatically pushes them to an org where the user has right to create tags. I'm not sure this should be part of pip-deepfreeze. It would probably be best as a standalone tool.

+1 to place this part into a standalone tool

**Comment by sbidoul** [comment] 2020-11-04 12:56
This will be part of the upcoming pip release, so closing this issue.

**Closed by sbidoul** 2020-11-04 12:56 UTC
Labels: question

**Comment by lmignon** [comment] 2020-11-04 15:04
OK thank you for the follow up.
